### ISSUE TITLE
probelem in installing

### ISSUE THREAD

**Issue by mehdi4467** [kleninmaxim/binance-api#2]
Hello
when i try to install i got this error
PHP Startup: Unable to load dynamic library 'curl' (tried: C:\php\ext\curl (The specified module could not be found), C:\php\ext\php_curl.dll (The specified module could not be found)) in Unknown on line 0

but my php is in below folder
C:\xampp\php

why it try to get from wrong folder?

**Comment by alisalehi1380** [comment]
Hey Dear mehdi4467. 

The error you're encountering indicates that PHP is trying to load the cURL extension (`php_curl.dll`), but it cannot find it in the specified directories (`C:\php\ext`). The message also mentions that it's attempting to load from `C:\php\ext\curl` and `C:\php\ext\php_curl.dll`.

Here are a few steps you can take to resolve the issue:

1. **Check PHP Configuration:**
   Ensure that the correct PHP configuration file (`php.ini`) is being used. You can check the loaded configuration file by creating a PHP script with the following content:

   ```php
   <?php
   phpinfo();
   ```

   Run this script in your browser and check the "Loaded Configuration File" to confirm that it corresponds to the PHP installation in `C:\xampp\php`.

2. **Correct Extension Directory:**
   In your `php.ini` file, make sure that the extension directory (`extension_dir`) is set correctly. It should point to the `ext` directory within your XAMPP PHP installation. For example:

   ```ini
   extension_dir = "C:\xampp\php\ext"
   ```

3. **Check for the cURL Extension:**
   Confirm that the `php_curl.dll` file exists in the specified extension directory (`C:\xampp\php\ext`). If it doesn't, you may need to reinstall PHP or enable the cURL extension.

4. **Path Environment Variable:**
   Check your system's PATH environment variable to make sure it includes the correct PHP directory (`C:\xampp\php`). This can affect which PHP installation is used by your system.

5. **Restart Apache:**
   After making changes to the PHP configuration, restart the Apache server to apply the changes.

If the issue persists, double-check the XAMPP installation and PHP configuration to ensure everything is set up correctly. Additionally, consider checking XAMPP forums or community resources for assistance with XAMPP-specific configurations and issues.
